### ISSUE TITLE
Worked with @angular/cli 8.2.3 but not worked with  @angular/cli 8.3.0

### ISSUE THREAD

**Issue by DmitriyIvanko** [manfredsteyer/ngx-build-plus#121]

**Comment by frederikdekegel** [comment]
I can confirm this issue. With @angular/cli@8.3.0, the build with differential enabled is no longer valid. The default angular builder apparently generates a build which is later on optimized once for es5 and once for es2015.

**Comment by lppedd** [comment]
Confirmed. Hope it will be resolved as it's essential for the future.

**Comment by frederikdekegel** [comment]
3 months later and finally having the time to look further into the issue, the problem for me did not arise from ngx-build-plus.

In my custom config, I was renaming the output files. However, with the changed build procedure, cli 8.3.x is relying on the fact that output javascript files end with - es5.js or - es2015.js in order to apply some post webpack build treatment. Because of the renaming, that treatment was no longer applied, causing a non valid build. 

After moving the renaming of the output files and from the config method to the post method and adding content replacements for runtime and index.html, all problems were resolved 😊
