### ISSUE TITLE
--extra-webpack-config not working with e2e Tests

### ISSUE THREAD

**Issue by hoeni** [manfredsteyer/ngx-build-plus#222]
How to use e2e-tests this way, it's not even taking the `--extra-webpack-config` option... (tried with a blank NG10 project and the example from here).

```
$ ng e2e --extra-webpack-config webpack.partial.js
Unknown option: '--extra-webpack-config'
Unknown option: 'webpack.partial.js'
How could I fix the e2e tests to use the webpack.partial.js ?
```

**Comment by manfredsteyer** [comment]
Hi Hoeni,

the reason for this is that the e2e builder is delegating to the builders for ng serve or ng build. Hence, we need to do this in ``angular.json``.

The e2e builder registered this way in ``angular.json``:

```
        "e2e": {
          "builder": "@angular-devkit/build-angular:protractor",
          "options": {
            "protractorConfig": "e2e/protractor.conf.js",
            "devServerTarget": "demo-app17:serve"
          },
          "configurations": {
            "production": {
              "devServerTarget": "demo-app17:serve:production"
            }
          }
        }
```

Hence, we need to configure the ``demo-app17:serve`` and/or ``demo-app17:production`` target.

The configuration for the first one could look like this:

````
        "serve": {
          "builder": "ngx-build-plus:dev-server",
          "options": {
            "browserTarget": "demo-app17:build",
            "singleBundle": true
          },
          "configurations": {
            "production": {
              "browserTarget": "demo-app17:build:production"
            }
          }
        },
```

Please also note that we need to use camelCase in angular.json. Hence, instead of ``single-bundle`` I'm using ``singleBundle`` here.

**Comment by WhyINeedToFillUsername** [comment]
@manfredsteyer I came here with the same issue. I understand that the e2e step is delegating build to the builders for ng serve and build. But I don't know how to add the required --extra-webpack-config option there? I don't see any hint of that in your answer.

@hoeni did you solve this please?

Help, pretty please :)

**Comment by WhyINeedToFillUsername** [comment]
FYI I switched to `@angular-builders/custom-webpack` (as suggested here https://stackoverflow.com/a/64007010/4255158, how-to here https://stackoverflow.com/a/51130803/4255158) and now my e2e tests are working with custom webpack config.
