### ISSUE TITLE
ngx-build-plus:externals not working for Angular 13 

### ISSUE THREAD

**Issue by choeller** [manfredsteyer/ngx-build-plus#314]
As Angular 13 is not producing UMD-Bundles anylonger the command

`ng g ngx-build-plus:externals --project  MY_PROJECT`

currently creates an invalid angular.json (pointing to the non-existing UMD-Bundles). 

Are there any plans to support externals for Angular 13 as well, or isn't that even possible?

**Comment by landonbuttars** [comment]
Would this cause this error? 
`An unhandled exception occurred: Cannot destructure property 'styles' of 'buildOptions.sourceMap' as it is undefined.`

Seems like ngx-build-plus is generating bad angular.json files.

**Comment by shayegh** [comment]
I have the same problem

**Comment by jsanta** [comment]
Hi. What's happening here is that since  Angular 12 (don't remember exactly what minor version), Angular doesn't  provide any umd bundles.
What I did to make externals run (cause haven't been able to make it  work....) is the following:

Edit your _angular.json_ file and  place the following scripts:
```
"scripts": [
              "./node_modules/rxjs/dist/bundles/rxjs.umd.js",
              "../angular-umd-bundle/dist/@angular/core/bundles/core.umd.js",
              "../angular-umd-bundle/dist/@angular/common/bundles/common.umd.js",
              "../angular-umd-bundle/dist/@angular/router/bundles/router.umd.js",
              "../angular-umd-bundle/dist/@angular/common/bundles/common-http.umd.js",
              "../angular-umd-bundle/dist/@angular/compiler/bundles/compiler.umd.js",
              "../angular-umd-bundle/dist/@angular/platform-browser/bundles/platform-browser.umd.js",
              "../angular-umd-bundle/dist/@angular/platform-browser-dynamic/bundles/platform-browser-dynamic.umd.js",
              "../angular-umd-bundle/dist/@angular/forms/bundles/forms.umd.js",
              "../angular-umd-bundle/dist/@angular/animations/bundles/animations.umd.js"
            ]
```

In a folder outside your project, clone the [angular-umd-bundle](https://github.com/mgechev/angular-umd-bundle) repo running  `git clone git@github.com:mgechev/angular-umd-bundle.git`

Adjust your _package.json_ file (angular-umd-bundle project) so it includes the following dependencies:
```
"dependencies": {
    "@angular/animations": "~13.0.0",
    "@angular/common": "~13.0.0",
    "@angular/compiler": "~13.0.0",
    "@angular/core": "~13.0.0",
    "@angular/forms": "~13.0.0",
    "@angular/platform-browser": "~13.0.0",
    "@angular/platform-browser-dynamic": "~13.0.0",
    "@angular/router": "~13.0.0",
    "rxjs": "~7.4.0",
    "tslib": "^2.3.0",
    "zone.js": "~0.11.4"
  }
```

Remember to install [rollup](https://rollupjs.org/guide/en/#installation).

Replace _rollup.config.js_ file with:
```
export default [
  {
    input: './node_modules/@angular/core/fesm2015/core.mjs',
    output: {
      file: './dist/@angular/core/bundles/core.umd.js',
      format: 'umd',
      name: 'ng.core'
    }
  },
  {
    input: './node_modules/@angular/common/fesm2015/common.mjs',
    output: {
      file: './dist/@angular/common/bundles/common.umd.js',
      format: 'umd',
      name: 'ng.common'
    }
  },
  {
    input: './node_modules/@angular/common/fesm2015/http.mjs',
    output: {
      file: './dist/@angular/common/bundles/common-http.umd.js',
      format: 'umd',
      name: 'ng.common.http'
    }
  },
  {
    input: './node_modules/@angular/platform-browser/fesm2015/platform-browser.mjs',
    output: {
      file: './dist/@angular/platform-browser/bundles/platform-browser.umd.js',
      format: 'umd',
      name: 'ng.platformBrowser'
    }
  },
  {
    input: './node_modules/@angular/platform-browser-dynamic/fesm2015/platform-browser-dynamic.mjs',
    output: {
      file: './dist/@angular/platform-browser-dynamic/bundles/platform-browser-dynamic.umd.js',
      format: 'umd',
      name: 'ng.platformBrowserDynamic'
    }
  },
  {
    input: './node_modules/@angular/compiler/fesm2015/compiler.mjs',
    output: {
      file: './dist/@angular/compiler/bundles/compiler.umd.js',
      format: 'umd',
      name: 'ng.compiler'
    }
  },
  {
    input: './node_modules/@angular/router/fesm2015/router.mjs',
    output: {
      file: './dist/@angular/router/bundles/router.umd.js',
      format: 'umd',
      name: 'ng.router'
    }
  },
  {
    input: './node_modules/@angular/forms/fesm2015/forms.mjs',
    output: {
      file: './dist/@angular/forms/bundles/forms.umd.js',
      format: 'umd',
      name: 'ng.forms'
    }
  },
  {
    input: './node_modules/@angular/animations/fesm2015/animations.mjs',
    output: {
      file: './dist/@angular/animations/bundles/animations.umd.js',
      format: 'umd',
      name: 'ng.animations'
    }
  },
];
```
Execute `npm run bundle` and wait.
Angular's UMD bundles should be created.

Go back to the original project, and run `npm run build:your-project:externals`
If it happens to fail check your referring the corect project name, and check the builder line on the build section of your _angular.json_ file:
`"builder": "ngx-build-plus:browser",`

In my findings it runs but it doesn't work. I'm getting:

`Uncaught TypeError: Cannot set properties of undefined (setting 'rxjs')`

Beware that the `ng serve` will seem to work correctly, but the builds will not.
Hope it helps  bit, at least to know where to look at.

**Comment by Condisil** [comment]
Hi @jsanta,

thank you very much for your first sketch. Based on your solution i get this working :).

Whats currently missing in the rollup configurations are the external dependencies. Because also the angular bundles require for example rxjs. So in the bundling process you have to specify in addition which dependencies are external and how they can be accessed,

For example my _(webpack/rollup).externals.js_ looks like this:
```
module.exports = {
  externals: {
    rxjs: 'rxjs',
    '@angular/core': 'ng.core',
    '@angular/common': 'ng.common',
    '@angular/common/http': 'ng.common.http',
    '@angular/platform-browser': 'ng.platformBrowser',
    '@angular/platform-browser-dynamic': 'ng.platformBrowserDynamic',
    '@angular/compiler': 'ng.compiler',
    '@angular/elements': 'ng.elements',
    '@angular/router': 'ng.router',
    '@angular/forms': 'ng.forms',
    'rxjs/operators': 'rxjs.operators',
  },
};
```
In rollup.config.js you have to specify for every file which dependencies are external and how they are named. For example to convert the _core.mjs_ file my _rollup.config.js_ looks like this :

```
const { externals } = require('./rollup.externals');

export default [
  {
    input: './node_modules/@angular/core/fesm2015/core.mjs',
    external: Object.keys(externals),
    output: {
      file: './dist/@angular/core/bundles/core.umd.js',
      format: 'umd',
      name: 'ng.core',
      globals: externals,
    },
  },
  ...
]
```
This has to be applied for all files. On important thing in addition the angular compiler should be loaded at first, otherwise there will be a runtime error. My _angular.json_ now looks like this:
```
"scripts": [
              "./node_modules/rxjs/dist/bundles/rxjs.umd.js",
              "../angular-umd-bundle/dist/@angular/compiler/bundles/compiler.umd.js",
              "../angular-umd-bundle/dist/@angular/core/bundles/core.umd.js",
              "../angular-umd-bundle/dist/@angular/common/bundles/common.umd.js",
              "../angular-umd-bundle/dist/@angular/router/bundles/router.umd.js",
              "../angular-umd-bundle/dist/@angular/common/bundles/common-http.umd.js",
              "../angular-umd-bundle/dist/@angular/platform-browser/bundles/platform-browser.umd.js",
              "../angular-umd-bundle/dist/@angular/platform-browser-dynamic/bundles/platform-browser-dynamic.umd.js",
              "../angular-umd-bundle/dist/@angular/forms/bundles/forms.umd.js",
              "../angular-umd-bundle/dist/@angular/animations/bundles/animations.umd.js"
            ]
``` 

Maybe we can find a way to include this conversion into the ngx-build-plus library it self to avoid the hassle to create another project for the angular dependencies. 

Hope it helps :)

**Comment by dtslvr** [comment]
I think this is related, I get the following errors:

```
Generating browser application bundles (phase: setup)...An unhandled exception occurred: Script file node_modules/@angular/core/bundles/core.umd.js does not exist.
See "/private/var/folders/q1/vg364k2s16z3w9czd5jxw_w80000gn/T/ng-cSuFS7/angular-errors.log" for further details.
```

```
[error] Error: Script file node_modules/@angular/core/bundles/core.umd.js does not exist.
    at /client/app/node_modules/@angular-devkit/build-angular/src/webpack/utils/helpers.js:157:23
    at Array.reduce (<anonymous>)
    at globalScriptsByBundleName (/client/app/node_modules/@angular-devkit/build-angular/src/webpack/utils/helpers.js:149:58)
    at getCommonConfig (/client/app/node_modules/@angular-devkit/build-angular/src/webpack/configs/common.js:102:89)
    at async Promise.all (index 1)
    at async generateWebpackConfig (/client/app/node_modules/@angular-devkit/build-angular/src/utils/webpack-browser-config.js:61:22)
    at async generateBrowserWebpackConfigFromContext (/client/app/node_modules/@angular-devkit/build-angular/src/utils/webpack-browser-config.js:123:20)
    at async generateI18nBrowserWebpackConfigFromContext (/client/app/node_modules/@angular-devkit/build-angular/src/utils/webpack-browser-config.js:70:20)
    at async setup (/client/app/node_modules/@angular-devkit/build-angular/src/builders/dev-server/index.js:127:47)
```

**Comment by SanmukhaniHarsh** [comment]
@jsanta the github link which you have provided is not working, it is asking for permissions to clone the repo. can you pls check once.

**Comment by jsanta** [comment]
@SanmukhaniHarsh try https://github.com/mgechev/angular-umd-bundle 
If you're having problems cloning the repo try using the http clone using the URL and your Github credentials.

If you tried the obove and still have problems cloning the repo I guess this link will be a  useful read: https://docs.github.com/es/authentication/connecting-to-github-with-ssh

**Comment by BastianMa** [comment]
@Condisil 
If i follow your instructions, i get this error (Angular 13.1.1) in the Browser with ng serve, but App works:

`Uncaught TypeError: Cannot read properties of undefined (reading 'InjectionToken')`

If i bundle it (ng build --extra-webpack-config ./webpack.externals.js --single-bundle) i get the same error plus this extra error and App doesn't work:

`Uncaught TypeError: Cannot read properties of undefined (reading 'ɵDomRendererFactory2')`

**Comment by ankushgoyal27** [comment]
Getting the same error 

Uncaught TypeError: Cannot read properties of undefined (reading 'InjectionToken')

**Comment by dimeloper** [comment]
getting the same error

```
Uncaught TypeError: Cannot read properties of undefined (reading 'InjectionToken')
```

any updates here?

**Comment by catiaraminhos** [comment]
> Is there any plan or intention to update the externals functionality so that this will continue to work on Angular 13+ or are the workarounds/hacks being discussed the only solution?

I'm also interested in this.

**Comment by peterblazejewicz** [comment]
hey folks, I've got this (rollup step, build step and properly serving app without any error) working (ng server, ng build, ng tests, etc) researching same problem (we have dozens of apps that share same code). Note, this is a reasearch project ro us at this moment:
https://github.com/peterblazejewicz/angular-umd-bundle

**Comment by kurtdl23** [comment]
I'm still getting the issue even after your project bundle peterblazejewicz

Uncaught TypeError: Cannot read properties of undefined (reading 'InjectionToken')
Uncaught TypeError: Cannot read properties of undefined (reading 'BrowserModule')

**Comment by peterblazejewicz** [comment]
@kurtdl23 no quick answer here. Can you make sure you're building and including UMD version of platform module (`angular/platform-browser`)?

**Comment by manfredsteyer** [comment]
The reason is that the Angular Package Format does not expose UMD anymore.

What about writing this into your main application:

window.ng.core = require('@angular/core');
window.ng.common = require('@angular/common');

**Comment by mrlukrative** [comment]
@manfredsteyer do you have an example?

**Comment by chan-dev** [comment]
@manfredsteyer, any updates on this one? An example would be great as suggested by @mrlukrative

**Comment by chan-dev** [comment]
> hi @peterblazejewicz , Yes, I am, this is line in my angular json
> 
> "angular-umd-bundle/dist/@angular/platform-browser/bundles/platform-browser.umd.js",
> 
> that is referring to the UMD version I build from the git repo. Weird thing is now the BrowserModule is gone but I'm left with the InjectionToken that everyone else above was getting.

Were you able to fix the error about `InjectionToken`?

**Comment by mrlukrative** [comment]
I found a solution that worked for me, here are the steps.

**Step 1.** 
In app.module.ts 
bootstrap should be empty. Add all that in the constructor.

import {Injector, NgModule} from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';

import { AppComponent } from './app.component';
import {createCustomElement} from '@angular/elements';

```
@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule
  ],
  providers: [],
  bootstrap: []
})
export class AppModule {
  constructor(injector: Injector) {
    const el = createCustomElement(AppComponent, {injector});
    customElements.define('my-element', el);
  }

  ngDoBooStrap() {}
}
```


**Step 2**
Create a file in the project root and give it the name 'build-script.js.'

Run ng build and take note of the build output files required for your project located in the dist folder. In my case, my sample project had just the following.

You'll need additional libraries. npm install the following:
npm install concat
npm install fs-extra

In the build-script.js file paste the following code and add whatever your might be missing in the const files list.

```
const fs = require('fs-extra');
const concat = require('concat');
(async function build() {
  const files = [
    './dist/ngElements/runtime.js',
    './dist/ngElements/polyfills.js',
    './dist/ngElements/main.js'
  ];
  await fs.ensureDir('elements')
  await concat(files, 'elements/my-element.js')
})();
```

**Step 3**
In your terminal run **node build-script**

**Comment by OuassimSABIR** [comment]
I used to have the same issue while using angular cli 13.3.6, but when I changed to angular cli 12.2.5 everything worked fine.
The problem with cli 13 is that it doesn't generate the bundles folder at all in angular core folder so I don't think it's possible to use ngrx build plus with angular cli 13

**Comment by peterblazejewicz** [comment]
@OuassimSABIR I've used 13.* for our use case, sample setup we've used:
https://github.com/peterblazejewicz/angular-umd-bundle
(mind, your details can be different)

**Comment by maranza** [comment]
> @OuassimSABIR I've used 13.* for our use case, sample setup we've used: https://github.com/peterblazejewicz/angular-umd-bundle (mind, your details can be different)

How do i implement on my project?

**Comment by peterblazejewicz** [comment]
@maranza this was a sample for very specific use case, using UMD modules (backward features compatibility when using UMD modules in code base, in case not all green browsers are used).
Minko Gechev project discussed above explains the approach, refer to the earlier discussion here

**Comment by slockwoo** [comment]
> @manfredsteyer do you have an example?

I got this working for me. I'm working with a shell with 2 remotes and 2 custom elements.

In a custom element, webpack.config.js, I put
`
externalsType: 'window',
externals: {
        '@angular/animations': 'ng.animations',
        '@angular/common': 'ng.common',
        '@angular/compiler': 'ng.compiler',
        '@angular/core': 'ng.core',
        '@angular/forms': 'ng.forms',
        '@angular/platform-browser': 'ng.platformBrowser',
        '@angular/platform-browser-dynamic': 'ng.platformBrowserDynamic',
        '@angular/router': 'ng.router'
    }
`
I started with only '@angular/core' but it was complaining about failed dependency injection, so tried it with all of the Angular dependencies and that error went away. I set externalsType to 'window' to reference the window when looking for the dependencies. A configuration described below adds the dependency references to the window.

In the shell, webpack.config.js, I put
`
module.exports = {
    plugins: [
        new ModuleFederationPlugin({
            shared: webpack.share({
                "@angular/animations": { eager: true, singleton: true, strictVersion: true, requiredVersion: 'auto' },
                "@angular/common": { eager: true, singleton: true, strictVersion: true, requiredVersion: 'auto' },
                "@angular/compiler": { eager: true, singleton: true, strictVersion: true, requiredVersion: 'auto' },
                "@angular/core": { eager: true, singleton: true, strictVersion: true, requiredVersion: 'auto' },
                "@angular/forms": { eager: true, singleton: true, strictVersion: true, requiredVersion: 'auto' },
                "@angular/platform-browser": { eager: true, singleton: true, strictVersion: true, requiredVersion: 'auto' },
                "@angular/platform-browser-dynamic": { eager: true, singleton: true, strictVersion: true, requiredVersion: 'auto' },
                "@angular/router": { eager: true, singleton: true, strictVersion: true, requiredVersion: 'auto' }
            })
        })
    ]
};
`
This was originally put in for the remote modules so it's not strictly required for custom elements. But if you have this code already for whatever reason, then they may need to add 'eager: true' to each dependency, otherwise the custom element may error on shared modules not being eagerly loaded.

In the shell, bootstrap.ts or anywhere before the custom element script is loaded, I put
`
declare var require: any;
(window as any)['ng.animations'] = require('@angular/animations');
(window as any)['ng.common'] = require('@angular/common');
(window as any)['ng.compiler'] = require('@angular/compiler');
(window as any)['ng.core'] = require('@angular/core');
(window as any)['ng.forms'] = require('@angular/forms');
(window as any)['ng.platformBrowser'] = require('@angular/platform-browser');
(window as any)['ng.platformBrowserDynamic'] = require('@angular/platform-browser-dynamic');
(window as any)['ng.router'] = require('@angular/router');
`
before loading AppModule or whatever you root level module is called. This adds the dependency references to the window so the custom element can reference the window to acquire the dependencies.

**Comment by edgarjoao** [comment]
Hi @slockwoo 
Do you have a github repo that I can take a look on your configuration using module federation for sharing libs?

Thanks

**Comment by ikeepfighting** [comment]
Hi @slockwoo 
If I update the angular version to 15.2.6, there will get the error: **Uncaught TypeError: Cannot read properties of undefined (reading 'ɵɵdefineComponent')**. Do you try it in angular 15 project?

Thanks!
