### ISSUE TITLE
Issue with polyfills...

### ISSUE THREAD

**Issue by NelsonLamprecht** [manfredsteyer/ngx-build-plus#52]
No repo yet but when output as a single bundle in prod mode, it appears the polyfill are not working. I've moved the zone.js file out and followed the guidance but when running in prod mode and single bundle, it appears to not work, (ie 11...). Anyone else have tips so I love the idea of a single bundle

**Comment by manfredsteyer** [comment]
Yes, this is by design. You just get a single bundle with things you would normally publish. It doesn't contain your polyfills, hence the consuming app has to import it by itself. 

But you can use the new switch --keep-polyfills alongside --single-bundle to get both, the single bundle + the polyfills for testing.
